name: Resume CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.versin }}
      - name: npm install and test
        run: |
          npm install
          npm test
